name: Deploy

on:
  workflow_run:
    workflows: ["Run Tests"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'main')
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
          Host my-vps
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: Redeploy Site
        run: |
          set -euo pipefail
          echo "=== running redeploy script on remote host ==="
          ssh my-vps "echo $ROOT_PASSWORD | sudo -S ~/redeploy-site.sh"
          echo "=== redeploy successful; syncing latest script copy ==="
          ssh my-vps 'yes | cp ~/graph-uf/scripts/redeploy-site.sh ~/redeploy-site.sh'
          echo "All remote commands finished."
        env:
          ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
