name: Run Tests
on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
      URL: localhost:5000
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Run Tests
        run: |
          python -m venv virtualenv
          virtualenv/bin/pip install -r requirements.txt
          python -m pytest
